homePage: /

dbrOverview: /dbr-basic-info/overview/

userGuide: /dbr-basic-info/user-guide/
userGuide_windows: /dbr-basic-info/user-guide/windows/
userGuide_linux: /dbr-basic-info/user-guide/linux/
userGuide_iOS: /dbr-basic-info/user-guide/ios/
userGuide_android: /dbr-basic-info/user-guide/android/
userGuide_wasm: /dbr-basic-info/user-guide/wasm/

evaluationTools: /dbr-basic-info/evaluation-tools/
evaluationTools_batchTestSuite: /dbr-basic-info/evaluation-tools/batch-test-suite/
evaluationTools_interactiveTest: /dbr-basic-info/evaluation-tools/interactive-test/
evaluationTools_testSetImages: /dbr-basic-info/evaluation-tools/test-set-images/

securityIssues: /dbr-basic-info/security-issues/  

manual: /dbr-detailed-info/manual/
manual_interface: /dbr-detailed-info/manual/interface/
manual_parameters: /dbr-detailed-info/manual/parameters/

demosSamples: /dbr-detailed-info/samples-and-demos/
demosSamples_appDemo: /dbr-detailed-info/samples-and-demos/
demosSamples_appDemo_ios: /dbr-detailed-info/samples-and-demos/ios/
demosSamples_appDemo_android: /dbr-detailed-info/samples-and-demos/android/
demosSamples_onlineDemo: /dbr-detailed-info/samples-and-demos/onlineDemo/
demosSamples_samples: /dbr-detailed-info/samples-and-demos/samples/

intermediateResults: /dbr-enhancements/intermediate-results/

dpm: /dbr-enhancements/dpm/

panoramaOverlap: /dbr-enhancements/panorama-and-overlap/

3dReconstruction: /dbr-enhancements/3d-reconstruction/

pdfVectors: /dbr-enhancements/pdf-vectors/  

industrialSolutions: /dbr-extended-info/industrial-solutions/

parameterUsage: /dbr-extended-info/how-to-use-parameters/

complicateImageHandling: /dbr-extended-info/how-to-handle-complicate-images/

licenseUsageTracking: /dbr-extended-info/license-and-usage-tracking/

barcodeBasisKnowledge: /dbr-extended-info/barcode-basis-knowledge/

imageProcessingKnowledge: /dbr-extended-info/image-processing-knowledge/ 


editIcon: /other-material/icon/editIcon.png
